# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lancaster University Roleplaying Society
email: lurps@lancaster.ac.uk
description: >
    LURPS is Lancaster University's society dedicated to roleplaying of all kinds, including tabletop and live action games.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.lurps.co.uk" # the base hostname & protocol for your site
twitter_username: hellolurps

# Build settings
markdown: kramdown
